# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone_number', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('status', models.CharField(choices=[('P', 'Paid'), ('U', 'UNPAID')], default='U', max_length=1)),
                ('descrition', models.TextField(help_text='write any description that will make yourlife easier ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('expiry', models.DateTimeField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Location')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
